create table DOCUMENTS 
(
ID_DOCUMENT int IDENTITY(1,1) PRIMARY KEY,
FID_JOURNAL int FOREIGN KEY REFERENCES Журнал(ID),
FID_TYPE_DOC int FOREIGN KEY REFERENCES ТипДокумента(ID),
NUM_RAZRESH varchar (255),
DATE_RAZRESH datetime,
TICKET_NUMBER varchar (255),
TICKET_DATE datetime
)
GO

