USE [Журнал_Main]
GO

/****** Object:  Table [dbo].[DOCUMENTS]    Script Date: 01.03.2017 11:40:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IDENTITY_TYPES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DOCTYPE] [int] NULL,
	[PROP_1] [varchar](50) NULL,
	[PROP_2] [varchar](50) NULL,
	[SCAN_LINK] [varchar](3500) NULL
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[IDENTITY_DOCS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DOCTYPE] [int] NULL,
	[PROP_1] [varchar](50) NULL,
	[PROP_2] [varchar](50) NULL,
	[SCAN_LINK] [varchar](3500) NULL
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

--Это тоже важно
--ALTER TABLE IDENTITY_TYPES ADD PRIMARY KEY (ID)

ALTER TABLE [dbo].[IDENTITY_DOCS] ADD FOREIGN KEY([DOCTYPE])
REFERENCES [dbo].[IDENTITY_TYPES] ([ID])
GO

ALTER TABLE [dbo].[Клиенты] ADD FOREIGN KEY([FID_Identity_Doc])
REFERENCES [dbo].[IDENTITY_DOCS] ([ID])
GO


