USE [Журнал_Main]
GO

/****** Object:  Table [dbo].[DOCUMENTS]    Script Date: 01.03.2017 11:40:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DOCUMENTS](
	[ID_DOCUMENT] [int] IDENTITY(1,1) NOT NULL,
	[FID_JOURNAL] [int] NULL,
	[FID_TYPE_DOC] [int] NULL,
	[NUM_RAZRESH] [varchar](50) NULL,
	[DATE_RAZRESH] [datetime] NULL,
	[TICKET_NUMBER] [varchar](50) NULL,
	[TICKET_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_DOCUMENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[DOCUMENTS]  WITH CHECK ADD FOREIGN KEY([FID_JOURNAL])
REFERENCES [dbo].[Журнал] ([ID])
GO

ALTER TABLE [dbo].[DOCUMENTS]  WITH CHECK ADD FOREIGN KEY([FID_TYPE_DOC])
REFERENCES [dbo].[ТипДокумента] ([ID])
GO


